Repository shoescream/backend, pull requests merged in 2024-06, with the labels that each got.

#40 [feat/kakao-pay] 배포 프로토콜 수정 http -> https
  src/main/java/com/sideproject/shoescream/bid/repository/DealRepository.java
  src/main/java/com/sideproject/shoescream/bid/service/BidService.java
  src/main/java/com/sideproject/shoescream/bid/service/DealService.java
  src/main/java/com/sideproject/shoescream/global/controller/StatusCheckController.java
  src/main/java/com/sideproject/shoescream/product/dto/response/ProductRankingResponse.java
  src/main/java/com/sideproject/shoescream/product/dto/response/ProductResponse.java
  src/main/java/com/sideproject/shoescream/product/repository/ProductOptionRepository.java
  src/main/java/com/sideproject/shoescream/product/util/ProductMapper.java
Labels: bug, enhancement

#41 [feat/bid] 상품 구매 + 결제 구현
  src/main/java/com/sideproject/shoescream/bid/service/BidService.java
  src/main/java/com/sideproject/shoescream/member/service/MemberService.java
  src/main/java/com/sideproject/shoescream/pay/controller/KakaoPayController.java
  src/main/java/com/sideproject/shoescream/pay/dto/KakaoApproveResponse.java
  src/main/java/com/sideproject/shoescream/pay/dto/KakaoPayInfoRequest.java
  src/main/java/com/sideproject/shoescream/pay/dto/KakaoReadyResponse.java
  src/main/java/com/sideproject/shoescream/pay/service/KakaoPayService.java
  src/main/resources/application.yaml
  src/test/java/com/sideproject/shoescream/member/service/MemberServiceTest.java
Labels: enhancement

#44 [feat/bid] 상품 구매 + 결제 구현
  src/main/java/com/sideproject/shoescream/pay/service/KakaoPayService.java
Labels: bug

#45 [feat/review] 리뷰 기능 구현
  build.gradle
  src/main/java/com/sideproject/shoescream/global/configuration/AwsConfiguration.java
  src/main/java/com/sideproject/shoescream/global/service/S3Service.java
  src/main/java/com/sideproject/shoescream/review/controller/ReviewController.java
  src/main/java/com/sideproject/shoescream/review/dto/request/ReviewPostRequest.java
  src/main/java/com/sideproject/shoescream/review/dto/response/ReviewResponse.java
  src/main/java/com/sideproject/shoescream/review/service/ReviewService.java
  src/main/java/com/sideproject/shoescream/review/util/ReviewMapper.java
  src/main/resources/application.yaml
Labels: enhancement

#46 [feat/bid] 상품 구매 + 결제 구현
  src/main/java/com/sideproject/shoescream/bid/controller/BidController.java
  src/main/java/com/sideproject/shoescream/bid/dto/response/BuyingProductInfoResponse.java
  src/main/java/com/sideproject/shoescream/bid/dto/response/SellingProductInfoResponse.java
  src/main/java/com/sideproject/shoescream/bid/entity/Bid.java
  src/main/java/com/sideproject/shoescream/bid/repository/BidRepository.java
  src/main/java/com/sideproject/shoescream/bid/service/BidService.java
  src/main/java/com/sideproject/shoescream/bid/util/BidMapper.java
  src/main/java/com/sideproject/shoescream/member/entity/Member.java
  src/main/java/com/sideproject/shoescream/notification/component/NotificationListener.java
  src/main/java/com/sideproject/shoescream/notification/constant/NotificationType.java
  src/main/java/com/sideproject/shoescream/notification/controller/NotificationController.java
  src/main/java/com/sideproject/shoescream/notification/dto/request/NotificationRequest.java
  src/main/java/com/sideproject/shoescream/notification/dto/response/NotificationResponse.java
  src/main/java/com/sideproject/shoescream/notification/entity/Notification.java
  src/main/java/com/sideproject/shoescream/notification/repository/EmitterRepository.java
  src/main/java/com/sideproject/shoescream/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/sideproject/shoescream/notification/repository/NotificationRepository.java
  src/main/java/com/sideproject/shoescream/notification/service/NotificationService.java
  src/test/java/com/sideproject/shoescream/notification/repository/EmitterRepositoryImplTest.java
  src/test/java/com/sideproject/shoescream/notification/service/NotificationServiceTest.java
Labels: enhancement

#47 기타 리팩토링
  src/main/java/com/sideproject/shoescream/bid/controller/BidController.java
  src/main/java/com/sideproject/shoescream/bid/service/BidService.java
  src/main/java/com/sideproject/shoescream/bid/service/DealService.java
  src/main/java/com/sideproject/shoescream/global/exception/ErrorCode.java
  src/main/java/com/sideproject/shoescream/product/exception/ProductNotFoundException.java
  src/main/java/com/sideproject/shoescream/product/service/ProductService.java
  src/test/java/com/sideproject/shoescream/product/controller/ProductControllerTest.java
Labels: enhancement

#48 [feat/review] 리뷰 기능 구현
  src/main/java/com/sideproject/shoescream/global/dto/response/Response.java
  src/main/java/com/sideproject/shoescream/review/controller/ReviewController.java
  src/main/java/com/sideproject/shoescream/review/dto/response/CommentResponse.java
  src/main/java/com/sideproject/shoescream/review/dto/response/ReviewCommentResponse.java
  src/main/java/com/sideproject/shoescream/review/dto/response/ReviewResponse.java
  src/main/java/com/sideproject/shoescream/review/entity/ReviewComment.java
  src/main/java/com/sideproject/shoescream/review/repository/CommentRepository.java
  src/main/java/com/sideproject/shoescream/review/repository/ReviewCommentRepository.java
  src/main/java/com/sideproject/shoescream/review/service/ReviewService.java
  src/main/java/com/sideproject/shoescream/review/util/ReviewMapper.java
Labels: enhancement

#49 [feat/review] 리뷰 기능 구현
  src/main/java/com/sideproject/shoescream/review/dto/request/ReviewCommentPostRequest.java
Labels: enhancement

#50 [feat/review] 리뷰 기능 구현
  src/main/java/com/sideproject/shoescream/review/controller/ReviewController.java
  src/main/java/com/sideproject/shoescream/review/dto/request/ReviewPostRequest.java
  src/main/java/com/sideproject/shoescream/review/dto/response/ReviewResponse.java
  src/main/java/com/sideproject/shoescream/review/repository/ReviewRepository.java
  src/main/java/com/sideproject/shoescream/review/service/ReviewService.java
Labels: enhancement

#51 feat: 구매 완료에 대한 리뷰 작성 상태 추가, 적용
  src/main/java/com/sideproject/shoescream/bid/entity/Deal.java
  src/main/java/com/sideproject/shoescream/member/dto/response/MyBuyingHistoryResponse.java
  src/main/java/com/sideproject/shoescream/member/util/MemberMapper.java
Labels: enhancement

#52 feat: 리뷰 작성 시 리뷰 작성 상태 변경 로직 추가
  src/main/java/com/sideproject/shoescream/review/service/ReviewService.java
Labels: enhancement

#53 feat: 구매자 리뷰 상태 타입 변경에 따라 로직 수정
  src/main/java/com/sideproject/shoescream/review/service/ReviewService.java
Labels: enhancement

#55 [feat/bid] 입찰 서비스 관련 수정
  src/main/java/com/sideproject/shoescream/bid/controller/BidController.java
  src/main/java/com/sideproject/shoescream/bid/service/BidService.java
  src/main/java/com/sideproject/shoescream/bid/util/DealMapper.java
Labels: bug, enhancement

#57 [feat/unit-test] 프로젝트 단위 테스트
  src/test/java/com/sideproject/shoescream/product/controller/ProductControllerTest.java
Labels: enhancement

#59 [feat/bid] 배포 환경에서 알림 오류 수정
  src/main/java/com/sideproject/shoescream/notification/repository/EmitterRepository.java
  src/main/java/com/sideproject/shoescream/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/sideproject/shoescream/notification/service/NotificationService.java
  src/test/java/com/sideproject/shoescream/notification/repository/EmitterRepositoryImplTest.java
  src/test/java/com/sideproject/shoescream/notification/service/NotificationServiceTest.java
Labels: bug, enhancement

#61 [feat/bid] sse 알림 dto response 수정
  src/main/java/com/sideproject/shoescream/bid/dto/response/BuyingBidResponse.java
  src/main/java/com/sideproject/shoescream/bid/entity/Bid.java
  src/main/java/com/sideproject/shoescream/bid/service/BidService.java
  src/main/java/com/sideproject/shoescream/bid/util/BidMapper.java
  src/main/java/com/sideproject/shoescream/member/controller/MemberController.java
  src/main/java/com/sideproject/shoescream/member/dto/response/MyNotificationResponse.java
  src/main/java/com/sideproject/shoescream/member/service/MemberService.java
  src/main/java/com/sideproject/shoescream/member/util/MemberMapper.java
  src/main/java/com/sideproject/shoescream/notification/component/NotificationListener.java
  src/main/java/com/sideproject/shoescream/notification/dto/request/NotificationRequest.java
  src/main/java/com/sideproject/shoescream/notification/dto/response/NotificationResponse.java
  src/main/java/com/sideproject/shoescream/notification/entity/Notification.java
  src/main/java/com/sideproject/shoescream/notification/repository/NotificationRepository.java
  src/main/java/com/sideproject/shoescream/notification/service/NotificationService.java
Labels: enhancement

#63 [feat/my-page] 리뷰 작성 마이페이지 조회 기능 추가
  src/main/java/com/sideproject/shoescream/bid/repository/DealRepository.java
  src/main/java/com/sideproject/shoescream/member/controller/MemberController.java
  src/main/java/com/sideproject/shoescream/member/dto/response/MyWritableReviewResponse.java
  src/main/java/com/sideproject/shoescream/member/service/MemberService.java
  src/main/java/com/sideproject/shoescream/member/util/MemberMapper.java
Labels: enhancement

#66 test: 알림 로직 변경에 의한 테스트 코드 수정
  src/test/java/com/sideproject/shoescream/notification/repository/EmitterRepositoryImplTest.java
  src/test/java/com/sideproject/shoescream/notification/service/NotificationServiceTest.java
Labels: enhancement

#67 입찰-거래-결제 프로세스 상태 점검하기
  src/main/java/com/sideproject/shoescream/bid/util/DealMapper.java
  src/main/java/com/sideproject/shoescream/pay/controller/KakaoPayController.java
  src/main/java/com/sideproject/shoescream/pay/dto/KakaoPayInfoRequest.java
  src/main/java/com/sideproject/shoescream/pay/service/KakaoPayService.java
Labels: enhancement

#68 입찰-거래-결제 프로세스 상태 점검하기
  src/main/java/com/sideproject/shoescream/bid/controller/BidController.java
  src/main/java/com/sideproject/shoescream/bid/dto/response/BuyingProductInfoResponse.java
  src/main/java/com/sideproject/shoescream/bid/service/BidService.java
  src/main/java/com/sideproject/shoescream/bid/util/BidMapper.java
Labels: enhancement

#69 리뷰 상태 에러 처리 수정
  src/main/java/com/sideproject/shoescream/review/service/ReviewService.java
Labels: bug

#70 [feat/unit-test] 프로젝트 단위 테스트
  src/test/java/com/sideproject/shoescream/member/service/MemberServiceTest.java
  src/test/java/com/sideproject/shoescream/product/service/ProductServiceTest.java
Labels: enhancement

#73 [Refactoring] 리뷰 도메인 코드 개선
  src/main/java/com/sideproject/shoescream/bid/controller/BidController.java
  src/main/java/com/sideproject/shoescream/bid/exception/DealNotFoundException.java
  src/main/java/com/sideproject/shoescream/bid/service/BidService.java
  src/main/java/com/sideproject/shoescream/global/exception/ErrorCode.java
  src/main/java/com/sideproject/shoescream/global/exception/GlobalExceptionAdvice.java
  src/main/java/com/sideproject/shoescream/member/configuration/AuthenticationConfiguration.java
  src/main/java/com/sideproject/shoescream/member/configuration/filter/JwtTokenFilter.java
  src/main/java/com/sideproject/shoescream/member/configuration/handler/CustomAccessDeniedHandler.java
  src/main/java/com/sideproject/shoescream/member/configuration/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/sideproject/shoescream/review/service/ReviewService.java
Labels: enhancement
